services:
  client-app:
    build: client
    volumes:
      - ./client/:/app/
    networks:
      - client-network
    ports:
      - "8080:8080"
  client-tunnel:
    image: cloudflare/cloudflared
    command: tunnel --url client-app:8080
    networks:
      - client-network
  server-app:
    build:
      context: server
      target: dev
    volumes:
      - ./server/:/app/
    networks:
      - server-network
    ports:
      - "3000:3000"
  server-tunnel:
    image: cloudflare/cloudflared
    command: tunnel --url server-app:3000
    networks:
      - server-network
networks:
  client-network:
  server-network:
