services:
  client:
    build: client
    volumes:
      - ./client:/app
    networks:
      - internal
    ports:
      - "8080:8080"
    restart: unless-stopped
  server:
    build:
      context: server
      target: dev
    volumes:
      - ./server:/app:ro
    networks:
      - internal
    ports:
      - "3000:3000"
    restart: unless-stopped
networks:
  internal:
