services:
  client-app:
    build: client
    env_file:
      - client.env
    volumes:
      - ./client/:/app/
    networks:
      - client-network
  client-tunnel:
    image: cloudflare/cloudflared
    command: tunnel --url client-app:8080
    networks:
      - client-network
  server-app:
    build:
      context: server
      target: dev
    env_file:
      - server.env
    volumes:
      - ./server/:/app/
    networks:
      - server-network
  server-tunnel:
    image: cloudflare/cloudflared
    command: tunnel --url server-app:3000
    networks:
      - server-network
networks:
  client-network:
  server-network:
