services:
  client-app:
    build: client
    environment:
      - VITE_DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
    volumes:
      - ./client/:/app/
    networks:
      - client-network
  client-tunnel:
    image: cloudflare/cloudflared
    command: tunnel --url client-app:8080
    networks:
      - client-network
  server-app:
    build:
      context: server
      target: dev
    environment:
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-unsecure}
    volumes:
      - ./server/:/app/
    networks:
      - server-network
    depends_on:
      - server-db
  server-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-unsecure}
    networks:
      - server-network
  server-adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - server-network
  server-tunnel:
    image: cloudflare/cloudflared
    command: tunnel --url server-app:3000
    networks:
      - server-network
networks:
  client-network:
  server-network:
